// Code generated by tools/gen-graphql. DO NOT EDIT.
//
// Source: central-ui/src/graphql/{queries,mutations}/**/*.ts
// Regenerate with: go generate ./operations
//
// The GraphQL documents below are generated from the Odigos Central UI
// sources (github.com/odigos-io/odigos-enterprise, central-ui) and are
// published by Odigos as part of this module under the Apache License 2.0.

package operations

// CREATE_CLOUD_CONNECTOR is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const CREATE_CLOUD_CONNECTOR = `mutation CreateCloudConnector($input: CreateCloudConnectorInput!) {
    createCloudConnector(input: $input) {
      created
      connectorId
      test {
        success
        accountId
        identity
        checks {
          name
          displayName
          passed
          message
          remediation
        }
      }
    }
  }`

// CREATE_GROUP_ROLE_MAPPING is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const CREATE_GROUP_ROLE_MAPPING = `mutation CreateGroupRoleMapping($input: WriteGroupRoleMappingInput!) {
    createGroupRoleMapping(input: $input) {
      success
      error
    }
  }`

// CREATE_TEAM is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const CREATE_TEAM = `mutation CreateTeam($input: WriteTeamInput!) {
    createTeam(input: $input) {
      success
      error
    }
  }`

// CREATE_USER is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const CREATE_USER = `mutation CreateUser($input: WriteUserInput!) {
    createUser(input: $input) {
      generatedPassword
      success
    }
  }`

// DELETE_CLOUD_CONNECTOR is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const DELETE_CLOUD_CONNECTOR = `mutation DeleteCloudConnector($connectorId: String!) {
    deleteCloudConnector(connectorId: $connectorId) {
      success
      error
    }
  }`

// DELETE_GROUP_ROLE_MAPPING is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const DELETE_GROUP_ROLE_MAPPING = `mutation DeleteGroupRoleMapping($providerId: AuthProviderId!, $id: String!) {
    deleteGroupRoleMapping(providerId: $providerId, id: $id) {
      success
      error
    }
  }`

// DELETE_PROXY_CONNECTION is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const DELETE_PROXY_CONNECTION = `mutation DeleteProxyConnection($proxyID: String!) {
    deleteProxyConnection(proxyID: $proxyID) {
      success
      error
    }
  }`

// DELETE_TEAM is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const DELETE_TEAM = `mutation DeleteTeam($teamID: String!) {
    deleteTeam(teamID: $teamID) {
      success
      error
    }
  }`

// DELETE_USER is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const DELETE_USER = `mutation DeleteUser($userID: String!) {
    deleteUser(userID: $userID) {
      success
      error
    }
  }`

// DOWNLOAD_DIAGNOSE is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const DOWNLOAD_DIAGNOSE = `query DownloadDiagnose($proxyID: String!, $input: DiagnoseInput, $dryRun: Boolean) {
    diagnose(proxyID: $proxyID, input: $input, dryRun: $dryRun) {
      stats {
        fileCount
        totalSizeBytes
        totalSizeHuman
      }
      includeProfiles
      includeMetrics
      includeSourceWorkloads
      sourceWorkloadNamespaces
    }
  }`

// ENSURE_OIDC_IDENTITY_PROVIDER is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const ENSURE_OIDC_IDENTITY_PROVIDER = `mutation EnsureOidcIdentityProvider($input: OidcIdentityProviderInput!) {
    ensureOidcIdentityProvider(input: $input) {
      success
      error
      callbackUrl
    }
  }`

// ENSURE_SAML_IDENTITY_PROVIDER is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const ENSURE_SAML_IDENTITY_PROVIDER = `mutation EnsureSamlIdentityProvider($input: SamlIdentityProviderInput!) {
    ensureSamlIdentityProvider(input: $input) {
      success
      error
      callbackUrl
    }
  }`

// GET_ALL_CLUSTER_SNAPSHOTS is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_ALL_CLUSTER_SNAPSHOTS = `query GetAllClusterSnapshots {
    allClusterSnapshots {
      clusters {
        clusterId
        clusterName
        namespaces {
          name
          selected
          workloads {
            namespace
            kind
            name
            selected
            otelServiceName
            healthStatus
          }
        }
        timestamp
      }
      totalWorkloads
      totalNamespaces
      lastUpdated
    }
  }`

// GET_CLOUD_CONNECTOR_PROVIDERS is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_CLOUD_CONNECTOR_PROVIDERS = `query GetCloudConnectorProviders {
    cloudConnectorProviders {
      provider
      displayName
      connectorFields {
        name
        displayName
        componentType
        componentProps
        required
        secret
        tooltip
        initialValue
        showInUi
        envVar
      }
      auth {
        permissions
        defaultMethod
        methods {
          id
          displayName
          description
          baseMethods
          fields {
            name
            displayName
            componentType
            componentProps
            required
            secret
            tooltip
            initialValue
            showInUi
            envVar
          }
        }
      }
      features {
        key
        enabled
        displayName
        description
        permissions
        types {
          name
          displayName
          description
          permissions
          method
          implemented
        }
      }
      setup {
        subtitle
        artifacts {
          id
          section
          variant
          variantLabel
          title
          description
          steps
          format
          template
          itemTemplate
          itemSeparator
        }
      }
    }
  }`

// GET_CLUSTER_SNAPSHOT is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_CLUSTER_SNAPSHOT = `query GetClusterSnapshot($clusterId: String!) {
    clusterSnapshot(clusterId: $clusterId) {
      clusterId
      clusterName
      namespaces {
        name
        selected
        workloads {
          namespace
          kind
          name
          selected
          otelServiceName
          healthStatus
        }
      }
      timestamp
    }
  }`

// GET_COMPUTE_PLATFORMS is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_COMPUTE_PLATFORMS = `query GetComputePlatforms {
    computePlatforms {
      id
      name
      odigosVersion
      graphqlSchemaVersion
      type
      status
      connectedAt
      lastSeenAt
      users {
        id
        email
        username
        role
      }
      teams {
        id
        name
      }
    }
  }`

// GET_CONFIGURED_IDENTITY_PROVIDERS is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_CONFIGURED_IDENTITY_PROVIDERS = `query ConfiguredIdentityProviders {
    configuredIdentityProviders
  }`

// GET_GROUP_ROLE_MAPPINGS is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_GROUP_ROLE_MAPPINGS = `query GetGroupRoleMappings($providerId: AuthProviderId!) {
    groupRoleMappings(providerId: $providerId) {
      id
      providerId
      claimName
      claimValue
      role
      displayName
    }
  }`

// GET_HEALTH is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_HEALTH = `query GetHealth {
    health {
      backend {
        redisStatus {
          status
          message
        }
        keycloakStatus {
          status
          message
        }
        sseStatus {
          status
          message
        }
      }
    }
  }`

// GET_SIGN_OUT_URL is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_SIGN_OUT_URL = `query GetSignOutUrl($idToken: String) {
    signOutUrl(idToken: $idToken)
  }`

// GET_SYSTEM_CONFIG is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_SYSTEM_CONFIG = `query GetSystemConfig {
    systemConfig {
      isInitialized
      version
    }
  }`

// GET_TEAMS is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_TEAMS = `query GetTeams {
    teams {
      id
      name
      description
      users {
        id
        email
        username
        role
      }
      computePlatforms {
        id
        name
      }
    }
  }`

// GET_USERS is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const GET_USERS = `query GetUsers {
    users {
      id
      email
      username
      role
      needsPasswordChange
    }
  }`

// REMOTE_FETCH is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const REMOTE_FETCH = `query RemoteFetch($proxyID: String!, $query: String!, $variables: JSON!) {
    remoteFetch(proxyID: $proxyID, query: $query, variables: $variables)
  }`

// REMOTE_MULTI_FETCH is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const REMOTE_MULTI_FETCH = `query RemoteMultiFetch($proxyIDs: [String!]!, $query: String!, $variables: JSON!) {
    remoteMultiFetch(proxyIDs: $proxyIDs, query: $query, variables: $variables) {
      proxyID
      success
      data
      error
    }
  }`

// SET_INITIAL_PASSWORD is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const SET_INITIAL_PASSWORD = `mutation SetInitialPassword($email: String!, $password: String!) {
    setInitialPassword(email: $email, password: $password) {
      idToken
      accessToken
      status
      user {
        id
        email
        username
        role
        needsPasswordChange
      }
    }
  }`

// SIGN_IN is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const SIGN_IN = `mutation SignIn($email: String, $password: String, $code: String) {
    signIn(email: $email, password: $password, code: $code) {
      idToken
      accessToken
      status
      user {
        id
        email
        username
        role
        needsPasswordChange
        teams {
          id
          name
          description
        }
        computePlatforms {
          id
          name
          type
          status
        }
      }
    }
  }`

// SIGN_IN_URL is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const SIGN_IN_URL = `query signInUrl($providerId: AuthProviderId!) {
    signInUrl(providerId: $providerId)
  }`

// TEST_CLOUD_CONNECTOR_CONNECTION is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const TEST_CLOUD_CONNECTOR_CONNECTION = `mutation TestCloudConnectorConnection($input: TestCloudConnectorConnectionInput!) {
    testCloudConnectorConnection(input: $input) {
      success
      accountId
      identity
      checks {
        name
        displayName
        passed
        message
        remediation
      }
    }
  }`

// UPDATE_COMPUTE_PLATFORM is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const UPDATE_COMPUTE_PLATFORM = `mutation UpdateComputePlatform($id: String!, $input: WriteComputePlatformInput!) {
    updateComputePlatform(id: $id, input: $input) {
      success
      error
    }
  }`

// UPDATE_GROUP_ROLE_MAPPING is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const UPDATE_GROUP_ROLE_MAPPING = `mutation UpdateGroupRoleMapping($id: String!, $input: WriteGroupRoleMappingInput!) {
    updateGroupRoleMapping(id: $id, input: $input) {
      success
      error
    }
  }`

// UPDATE_TEAM is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const UPDATE_TEAM = `mutation UpdateTeam($teamID: String!, $input: WriteTeamInput!) {
    updateTeam(teamID: $teamID, input: $input) {
      success
      error
    }
  }`

// UPDATE_USER is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const UPDATE_USER = `mutation UpdateUser($userID: String!, $input: WriteUserInput!) {
    updateUser(userID: $userID, input: $input) {
      success
      error
    }
  }`

// VERIFY_TOKEN is a central-scoped GraphQL operation. It does not vary by
// proxy version because it targets Central directly.
const VERIFY_TOKEN = `mutation VerifyToken($token: String!) {
    verifyToken(token: $token) {
      success
      error
    }
  }`
