//go:generate go run ../tools/gen-graphql -source $ODIGOS_ENTERPRISE_PATH -out .

// Package operations holds versioned GraphQL operation definitions used by
// the Odigos Central Go client.
//
// Two kinds of operations live here:
//
//  1. Central-scoped operations (signIn, computePlatforms, systemConfig,
//     remoteFetch). These are versioned with the Central server itself; for
//     each we keep a single GraphQL string. They live in central_ops.go
//     (which is generated by tools/gen-graphql from central-ui/src/graphql/
//     {queries,mutations}/*.ts).
//
//  2. Cluster-scoped operations executed via Central's remoteFetch proxy.
//     Each can have multiple variants keyed by (platform.Type, version.Version).
//     They live in remote_queries.go / remote_mutations.go (also generated).
//
// At runtime the client picks the appropriate variant for a given proxy by
// calling Operation.Pick, which mirrors central-ui's getVersionedQuery
// helper: it returns the highest registered variant whose minimum version is
// less than or equal to the proxy's actual version.
package operations

import (
	"sort"

	"github.com/odigos-io/odigos-central-client/platform"
	"github.com/odigos-io/odigos-central-client/version"
)

// Operation models a versioned GraphQL operation.
//
// Variants is keyed first by compute-platform type, then by the *minimum*
// Odigos version at which that variant became available. The string value is
// the GraphQL operation document (a complete `query` or `mutation`).
type Operation struct {
	// Name is the GraphQL operation name (e.g. "GetSources"). Used in errors
	// and for logging only.
	Name string

	// Variants maps a platform type to a map of (minimum-version -> document).
	Variants map[platform.Type]map[version.Version]string
}

// Pick returns the GraphQL document that should be sent for an operation
// targeting a proxy whose advertised version is `want` and whose platform
// type is `pt`. It selects the highest registered variant whose minimum
// version is <= want.
//
// Returns *UnsupportedPlatformError when the operation has no variants for
// the requested platform, or *UnsupportedVersionError when no registered
// variant for the platform is supported at or below `want`.
func (op *Operation) Pick(pt platform.Type, want version.Version) (string, error) {
	if op == nil {
		return "", &UnsupportedPlatformError{Op: "<nil>", Platform: pt}
	}
	pvariants, ok := op.Variants[pt]
	if !ok || len(pvariants) == 0 {
		return "", &UnsupportedPlatformError{Op: op.Name, Platform: pt}
	}

	versions := make([]version.Version, 0, len(pvariants))
	for v := range pvariants {
		versions = append(versions, v)
	}
	sort.Slice(versions, func(i, j int) bool { return versions[i].Compare(versions[j]) > 0 })

	for _, v := range versions {
		if want.GTE(v) {
			return pvariants[v], nil
		}
	}

	return "", &UnsupportedVersionError{
		Op:       op.Name,
		Platform: pt,
		Want:     want,
		Min:      versions[len(versions)-1],
	}
}

// SupportedPlatforms reports the set of platforms that the operation has at
// least one registered variant for. The returned slice is stable-sorted by
// the underlying string form so call sites can render deterministic errors.
func (op *Operation) SupportedPlatforms() []platform.Type {
	if op == nil {
		return nil
	}
	out := make([]platform.Type, 0, len(op.Variants))
	for p, variants := range op.Variants {
		if len(variants) == 0 {
			continue
		}
		out = append(out, p)
	}
	sort.Slice(out, func(i, j int) bool { return string(out[i]) < string(out[j]) })
	return out
}

// MinVersion returns the lowest registered version for a given platform, or
// (zero, false) if there are no variants for that platform.
func (op *Operation) MinVersion(pt platform.Type) (version.Version, bool) {
	if op == nil {
		return version.Version{}, false
	}
	pvariants, ok := op.Variants[pt]
	if !ok || len(pvariants) == 0 {
		return version.Version{}, false
	}
	var min version.Version
	first := true
	for v := range pvariants {
		if first || v.Compare(min) < 0 {
			min = v
			first = false
		}
	}
	return min, true
}
