// Code generated by tools/gen-graphql. DO NOT EDIT.
//
// Source: central-ui/src/graphql/{queries,mutations}/**/*.ts
// Regenerate with: go generate ./operations

package operations

import (
	"github.com/odigos-io/odigos-central-client/platform"
	"github.com/odigos-io/odigos-central-client/version"
)

// GET_ACTIONS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_ACTIONS = Operation{
	Name: "GET_ACTIONS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.29"): `query GetActions {
      computePlatform {
        actions {
          id
          type
          name
          notes
          disabled
          signals
          fields {
            collectContainerAttributes
            collectReplicaSetAttributes
            collectWorkloadId
            collectClusterId
            labelsAttributes {
              labelKey
              attributeKey
              from
              fromSources
            }
            annotationsAttributes {
              annotationKey
              attributeKey
              from
              fromSources
            }
            clusterAttributes {
              attributeName
              attributeStringValue
            }
            overwriteExistingValues
            attributeNamesToDelete
            renames
            piiCategories
            extractAttribute {
              extractions {
                targetAttributeName
                lookupKey
                dataFormat
                regex
              }
            }
            urlTemplatizationRulesGroups {
              filterK8sNamespace
              filterK8sWorkloadKind
              filterK8sWorkloadName
              filterProgrammingLanguage
              notes
              workloadFilters {
                kind
                name
              }
              templatizationRules {
                template
                notes
                examples
              }
            }
          }
          conditions {
            status
            type
            reason
            message
          }
        }
      }
    }`,
			version.MustParse("v1.28"): `query GetActions {
      computePlatform {
        actions {
          id
          type
          name
          notes
          disabled
          signals
          fields {
            collectContainerAttributes
            collectReplicaSetAttributes
            collectWorkloadId
            collectClusterId
            labelsAttributes {
              labelKey
              attributeKey
              from
              fromSources
            }
            annotationsAttributes {
              annotationKey
              attributeKey
              from
              fromSources
            }
            clusterAttributes {
              attributeName
              attributeStringValue
            }
            overwriteExistingValues
            attributeNamesToDelete
            renames
            piiCategories
            urlTemplatizationRulesGroups {
              filterK8sNamespace
              filterK8sWorkloadKind
              filterK8sWorkloadName
              filterProgrammingLanguage
              notes
              workloadFilters {
                kind
                name
              }
              templatizationRules {
                template
                notes
                examples
              }
            }
          }
          conditions {
            status
            type
            reason
            message
          }
        }
      }
    }`,
			version.MustParse("v1.20"): `query GetActions {
    computePlatform {
      actions {
        id
        type
        name
        notes
        disabled
        signals
        fields {
          collectContainerAttributes
          collectReplicaSetAttributes
          collectWorkloadId
          collectClusterId
          labelsAttributes {
            labelKey
            attributeKey
            from
            fromSources
          }
          annotationsAttributes {
            annotationKey
            attributeKey
            from
            fromSources
          }
          clusterAttributes {
            attributeName
            attributeStringValue
          }
          overwriteExistingValues
          attributeNamesToDelete
          renames
          piiCategories
          samplingPercentage
          fallbackSamplingRatio
          endpointsFilters {
            httpRoute
            serviceName
            minimumLatencyThreshold
            fallbackSamplingRatio
          }
          servicesNameFilters {
            serviceName
            samplingRatio
            fallbackSamplingRatio
          }
          attributeFilters {
            serviceName
            attributeKey
            fallbackSamplingRatio
            condition {
              stringCondition {
                operation
                expectedValue
              }
            }
          }
        }
        conditions {
          status
          type
          reason
          message

        }
      }
    }
  }`,
		},
	},
}

// GET_COLLECTOR_POD_INFO is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_COLLECTOR_POD_INFO = Operation{
	Name: "GET_COLLECTOR_POD_INFO",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetCollectorPodDetails($namespace: String!, $name: String!) {
    collectorPod(namespace: $namespace, name: $name) {
      namespace
      name
      node
      status
      containers {
        name
        image
        status
        stateReason
        ready
        started
        restarts
        startedAt
        resources {
          requests {
            cpu
            memory
          }
          limits {
            cpu
            memory
          }
        }
      }
      manifestYAML
    }
  }`,
		},
	},
}

// GET_CONFIG is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_CONFIG = Operation{
	Name: "GET_CONFIG",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetConfig {
    config {
      tier
      readonly
      installationMethod
      installationStatus
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetConfig {
    config {
      tier
      readonly
      installationMethod
      installationStatus
    }
  }`,
		},
	},
}

// GET_CONFIG_YAMLS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_CONFIG_YAMLS = Operation{
	Name: "GET_CONFIG_YAMLS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.26"): `query GetConfigYamls {
      configYamls {
        name
        displayName
        fields {
          displayName
          componentType
          isHelmOnly
          isEnterpriseOnly
          description
          helmValuePath
          docsLink
          componentProps
          renderCondition
        }
      }
    }`,
			version.MustParse("v1.24"): `query GetConfigYamls {
      configYamls {
        name
        displayName
        fields {
          displayName
          componentType
          isHelmOnly
          isEnterpriseOnly
          description
          helmValuePath
          docsLink
          componentProps
        }
      }
    }`,
			version.MustParse("v1.20"): `query GetConfigYamls {
    configYamls {
      name
      displayName
      fields {
        displayName
        componentType
        isHelmOnly
        description
        helmValuePath
        docsLink
        componentProps
      }
    }
  }`,
		},
	},
}

// GET_DATA_STREAMS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_DATA_STREAMS = Operation{
	Name: "GET_DATA_STREAMS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetDataStreams {
    computePlatform {
      dataStreams {
        name
      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetDataStreams {
    computePlatform {
      dataStreams {
        name
      }
    }
  }`,
		},
	},
}

// GET_DESCRIBE_ODIGOS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_DESCRIBE_ODIGOS = Operation{
	Name: "GET_DESCRIBE_ODIGOS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query DescribeOdigos {
    describeOdigos {
      odigosVersion {
        name
        value
        status
        explain
      }
      kubernetesVersion {
        name
        value
        status
        explain
      }
      tier {
        name
        value
        status
        explain
      }
      installationMethod {
        name
        value
        status
        explain
      }
      numberOfDestinations
      numberOfSources
      clusterCollector {
        enabled {
          name
          value
          status
          explain
        }
        collectorGroup {
          name
          value
          status
          explain
        }
        deployed {
          name
          value
          status
          explain
        }
        deployedError {
          name
          value
          status
          explain
        }
        collectorReady {
          name
          value
          status
          explain
        }
        deploymentCreated {
          name
          value
          status
          explain
        }
        expectedReplicas {
          name
          value
          status
          explain
        }
        healthyReplicas {
          name
          value
          status
          explain
        }
        failedReplicas {
          name
          value
          status
          explain
        }
        failedReplicasReason {
          name
          value
          status
          explain
        }
      }
      nodeCollector {
        enabled {
          name
          value
          status
          explain
        }
        collectorGroup {
          name
          value
          status
          explain
        }
        deployed {
          name
          value
          status
          explain
        }
        deployedError {
          name
          value
          status
          explain
        }
        collectorReady {
          name
          value
          status
          explain
        }
        daemonSet {
          name
          value
          status
          explain
        }
        desiredNodes {
          name
          value
          status
          explain
        }
        currentNodes {
          name
          value
          status
          explain
        }
        updatedNodes {
          name
          value
          status
          explain
        }
        availableNodes {
          name
          value
          status
          explain
        }
      }
    }
  }`,
		},
	},
}

// GET_DESCRIBE_SOURCE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_DESCRIBE_SOURCE = Operation{
	Name: "GET_DESCRIBE_SOURCE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query DescribeSource($namespace: String!, $kind: String!, $name: String!) {
    describeSource(namespace: $namespace, kind: $kind, name: $name) {
      totalPods
      podsPhasesCount
      pods {
        podName {
          name
          value
          status
          explain
        }
        nodeName {
          name
          value
          status
          explain
        }
        phase {
          name
          value
          status
          explain
        }
        agentInjected {
          name
          value
          status
          explain
        }
        runningLatestWorkloadRevision {
          name
          value
          status
          explain
        }
        containers {
          containerName {
            name
            value
            status
            explain
          }
          actualDevices {
            name
            value
            status
            explain
          }
          started {
            name
            value
            status
            explain
          }
          ready {
            name
            value
            status
            explain
          }
          instrumentationInstances {
            healthy {
              name
              value
              status
              explain
            }
            message {
              name
              value
              status
              explain
            }
            identifyingAttributes {
              name
              value
              status
              explain
            }
          }
        }
        manifestYAML
      }
    }
  }`,
		},
	},
}

// GET_DESTINATIONS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_DESTINATIONS = Operation{
	Name: "GET_DESTINATIONS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetDestinations {
    computePlatform {
      destinations {
        id
        name
        disabled
        dataStreamNames
        fields
        exportedSignals {
          logs
          metrics
          traces
        }
        destinationType {
          type
          imageUrl
          displayName
          supportedSignals {
            logs {
              supported
            }
            metrics {
              supported
            }
            traces {
              supported
            }
          }
        }
        conditions {
          status
          type
          reason
          message

        }
      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetDestinations {
    computePlatform {
      destinations {
        id
        name
        disabled
        dataStreamNames
        fields
        exportedSignals {
          logs
          metrics
          traces
        }
        destinationType {
          type
          imageUrl
          displayName
          supportedSignals {
            logs {
              supported
            }
            metrics {
              supported
            }
            traces {
              supported
            }
          }
        }
        conditions {
          status
          type
          reason
          message

        }
      }
    }
  }`,
		},
	},
}

// GET_DESTINATION_CATEGORIES is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_DESTINATION_CATEGORIES = Operation{
	Name: "GET_DESTINATION_CATEGORIES",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetDestinationCategories {
    destinationCategories {
      categories {
        name
        description
        items {
          type
          testConnectionSupported
          displayName
          imageUrl
          supportedSignals {
            logs {
              supported
            }
            metrics {
              supported
            }
            traces {
              supported
            }
          }
          fields {
            name
            displayName
            componentType
            componentProperties
            secret
            initialValue
            renderCondition
            hideFromReadData
            customReadDataLabels {
              condition
              title
              value
            }
          }
        }
      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetDestinationCategories {
    destinationCategories {
      categories {
        name
        description
        items {
          type
          testConnectionSupported
          displayName
          imageUrl
          supportedSignals {
            logs {
              supported
            }
            metrics {
              supported
            }
            traces {
              supported
            }
          }
          fields {
            name
            displayName
            componentType
            componentProperties
            secret
            initialValue
            renderCondition
            hideFromReadData
            customReadDataLabels {
              condition
              title
              value
            }
          }
        }
      }
    }
  }`,
		},
	},
}

// GET_EFFECTIVE_CONFIG is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_EFFECTIVE_CONFIG = Operation{
	Name: "GET_EFFECTIVE_CONFIG",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.25"): `query GetEffectiveConfig {
    effectiveConfig {
      configVersion
      telemetryEnabled
      openshiftEnabled
      ignoredNamespaces
      ignoredContainers
      ignoreOdigosNamespace
      psp
      imagePrefix
      skipWebhookIssuerCreation
      collectorGateway {
        minReplicas
        maxReplicas
        requestMemoryMiB
        limitMemoryMiB
        requestCPUm
        limitCPUm
        memoryLimiterLimitMiB
        memoryLimiterSpikeLimitMiB
        goMemLimitMiB
        serviceGraphDisabled
        clusterMetricsEnabled
        httpsProxyAddress
        nodeSelector
      }
      collectorNode {
        collectorOwnMetricsPort
        requestMemoryMiB
        limitMemoryMiB
        requestCPUm
        limitCPUm
        memoryLimiterLimitMiB
        memoryLimiterSpikeLimitMiB
        goMemLimitMiB
        k8sNodeLogsDirectory
        enableDataCompression
        otlpExporterConfiguration {
          enableDataCompression
          timeout
          retryOnFailure {
            enabled
            initialInterval
            maxInterval
            maxElapsedTime
          }
        }
      }
      profiles
      allowConcurrentAgents {
        enabled
      }
      uiMode
      uiPaginationLimit
      uiRemoteUrl
      centralBackendURL
      clusterName
      instrumentor {
        mountMethod
        agentEnvVarsInjectionMethod
        checkDeviceHealthBeforeInjection
      }
      customContainerRuntimeSocketPath
      userInstrumentationEnvs {
        languages
      }
      nodeSelector
      karpenter {
        enabled
      }
      rollout {
        automaticRolloutDisabled
        maxConcurrentRollouts
      }
      autoRollback {
        disabled
        graceTime
        stabilityWindowTime
      }
      oidc {
        tenantUrl
        clientId
        clientSecret
      }
      odigletHealthProbeBindPort
      goAutoOffsetsCron
      goAutoOffsetsMode
      clickhouseJsonTypeEnabled
      resourceSizePreset
      wasp {
        enabled
      }
      metricsSources {
        spanMetrics {
          disabled
          interval
          metricsExpiration
          additionalDimensions
          histogramDisabled
          histogramBuckets
          includedProcessInDimensions
          excludedResourceAttributes
          resourceMetricsKeyAttributes
        }
        hostMetrics {
          disabled
          interval
        }
        kubeletStats {
          disabled
          interval
        }
        odigosOwnMetrics {
          interval
        }
        agentMetrics {
          spanMetrics {
            enabled
          }
          runtimeMetrics {
            java {
              disabled
              metrics {
                name
                disabled
              }
            }
          }
        }
      }
      agentsInitContainerResources {
        requestCPUm
        limitCPUm
        requestMemoryMiB
        limitMemoryMiB
      }
      traceIdSuffix
      allowedTestConnectionHosts
      odigosOwnTelemetryStore {
        metricsStoreDisabled
      }
      imagePullSecrets
      componentLogLevels {
        default
        autoscaler
        scheduler
        instrumentor
        odiglet
        deviceplugin
        ui
        collector
      }
      sampling {
        dryRun
        spanSamplingAttributes {
          disabled
          samplingCategoryDisabled
          traceDecidingRuleDisabled
          spanDecisionAttributesDisabled
        }
        tailSampling {
          disabled
          traceAggregationWaitDuration
        }
        k8sHealthProbesSampling {
          enabled
          keepPercentage
        }
      }
      profiling {
        enabled
      }
      provenance {
        helmPath
        reconciledFrom
      }
      manifestYAML
    }
  }`,
			version.MustParse("v1.24"): `query GetEffectiveConfig {
    effectiveConfig {
      configVersion
      telemetryEnabled
      openshiftEnabled
      ignoredNamespaces
      ignoredContainers
      ignoreOdigosNamespace
      psp
      imagePrefix
      skipWebhookIssuerCreation
      collectorGateway {
        minReplicas
        maxReplicas
        requestMemoryMiB
        limitMemoryMiB
        requestCPUm
        limitCPUm
        memoryLimiterLimitMiB
        memoryLimiterSpikeLimitMiB
        goMemLimitMiB
        serviceGraphDisabled
        clusterMetricsEnabled
        httpsProxyAddress
        nodeSelector
      }
      collectorNode {
        collectorOwnMetricsPort
        requestMemoryMiB
        limitMemoryMiB
        requestCPUm
        limitCPUm
        memoryLimiterLimitMiB
        memoryLimiterSpikeLimitMiB
        goMemLimitMiB
        k8sNodeLogsDirectory
        enableDataCompression
        otlpExporterConfiguration {
          enableDataCompression
          timeout
          retryOnFailure {
            enabled
            initialInterval
            maxInterval
            maxElapsedTime
          }
        }
      }
      profiles
      allowConcurrentAgents {
        enabled
      }
      uiMode
      uiPaginationLimit
      uiRemoteUrl
      centralBackendURL
      clusterName
      instrumentor {
        mountMethod
        agentEnvVarsInjectionMethod
        checkDeviceHealthBeforeInjection
      }
      customContainerRuntimeSocketPath
      userInstrumentationEnvs {
        languages
      }
      nodeSelector
      karpenter {
        enabled
      }
      rollout {
        automaticRolloutDisabled
      }
      autoRollback {
        disabled
        graceTime
        stabilityWindowTime
      }
      oidc {
        tenantUrl
        clientId
        clientSecret
      }
      odigletHealthProbeBindPort
      goAutoOffsetsCron
      goAutoOffsetsMode
      clickhouseJsonTypeEnabled
      resourceSizePreset
      wasp {
        enabled
      }
      metricsSources {
        spanMetrics {
          disabled
          interval
          metricsExpiration
          additionalDimensions
          histogramDisabled
          histogramBuckets
          includedProcessInDimensions
          excludedResourceAttributes
          resourceMetricsKeyAttributes
        }
        hostMetrics {
          disabled
          interval
        }
        kubeletStats {
          disabled
          interval
        }
        odigosOwnMetrics {
          interval
        }
        agentMetrics {
          spanMetrics {
            enabled
          }
          runtimeMetrics {
            java {
              disabled
              metrics {
                name
                disabled
              }
            }
          }
        }
      }
      agentsInitContainerResources {
        requestCPUm
        limitCPUm
        requestMemoryMiB
        limitMemoryMiB
      }
      traceIdSuffix
      allowedTestConnectionHosts
      odigosOwnTelemetryStore {
        metricsStoreDisabled
      }
      imagePullSecrets
      componentLogLevels {
        default
        autoscaler
        scheduler
        instrumentor
        odiglet
        deviceplugin
        ui
        collector
      }
      provenance {
        helmPath
        reconciledFrom
      }
      manifestYAML
    }
  }`,
			version.MustParse("v1.20"): `query GetEffectiveConfig {
    effectiveConfig {
      rollout {
        automaticRolloutDisabled
      }
    }
  }`,
		},
	},
}

// GET_GATEWAY_INFO is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_GATEWAY_INFO = Operation{
	Name: "GET_GATEWAY_INFO",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GatewayDeploymentInfo {
    gatewayDeploymentInfo {
      status
      hpa {
        min
        max
        current
        desired
        conditions {
          status
          type
          reason
          message

        }
      }
      resources {
        requests {
          cpu
          memory
        }
        limits {
          cpu
          memory
        }
      }
      imageVersion
      lastRolloutAt
      rolloutInProgress
      manifestYAML
      configMapYAML
    }
  }`,
		},
	},
}

// GET_GATEWAY_PODS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_GATEWAY_PODS = Operation{
	Name: "GET_GATEWAY_PODS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GatewayPods {
    gatewayPods {
      namespace
      name
      status
      restartsCount
      nodeName
      creationTimestamp
      image
      collectorMetrics {
        metricsAcceptedRps
        metricsDroppedRps
        exporterSuccessRps
        exporterFailedRps
        window
        lastScrape
      }
    }
  }`,
		},
	},
}

// GET_INSTRUMENTATION_RULES is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_INSTRUMENTATION_RULES = Operation{
	Name: "GET_INSTRUMENTATION_RULES",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.28"): `query GetInstrumentationRules {
    computePlatform {
      instrumentationRules {
        type
        ruleId
        ruleName
        notes
        disabled
        mutable
        profileName
        sourcesScopes { sources { namespace kind name }
  namespaces
  languages }
        conditions {
          status
          type
          reason
          message

        }
        payloadCollection {
          httpRequest {
            mimeTypes
            maxPayloadLength
            dropPartialPayloads
          }
          httpResponse {
            mimeTypes
            maxPayloadLength
            dropPartialPayloads
          }
          dbQuery {
            maxPayloadLength
            dropPartialPayloads
          }
          messaging {
            maxPayloadLength
            dropPartialPayloads
          }
        }
        codeAttributes {
          column
          filePath
          function
          lineNumber
          namespace
          stacktrace
        }
        headersCollection {
          headerKeys
        }
        customInstrumentations {
          golang {
            packageName
            functionName
            receiverName
            receiverMethodName
          }
          java {
            methodName
            className
          }
        }
      }
    }
  }`,
			version.MustParse("v1.20"): `query GetInstrumentationRules {
    computePlatform {
      instrumentationRules {
        type
        ruleId
        ruleName
        notes
        disabled
        mutable
        profileName
        conditions {
          status
          type
          reason
          message

        }
        payloadCollection {
          httpRequest {
            mimeTypes
            maxPayloadLength
            dropPartialPayloads
          }
          httpResponse {
            mimeTypes
            maxPayloadLength
            dropPartialPayloads
          }
          dbQuery {
            maxPayloadLength
            dropPartialPayloads
          }
          messaging {
            maxPayloadLength
            dropPartialPayloads
          }
        }
        codeAttributes {
          column
          filePath
          function
          lineNumber
          namespace
          stacktrace
        }
        headersCollection {
          headerKeys
        }
        customInstrumentations {
          golang {
            packageName
            functionName
            receiverName
            receiverMethodName
          }
          java {
            methodName
            className
          }
        }
      }
    }
  }`,
		},
	},
}

// GET_K8S_MANIFEST is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_K8S_MANIFEST = Operation{
	Name: "GET_K8S_MANIFEST",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetK8sManifest($namespace: String!, $kind: K8sResourceKind!, $name: String!) {
    k8sManifest(namespace: $namespace, kind: $kind, name: $name)
  }`,
		},
	},
}

// GET_METRICS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_METRICS = Operation{
	Name: "GET_METRICS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetOverviewMetrics {
    getOverviewMetrics {
      sources {
        namespace
        kind
        name
        totalDataSent
        throughput
      }
      destinations {
        id
        totalDataSent
        throughput
      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetOverviewMetrics {
    getOverviewMetrics {
      sources {
        namespace
        kind
        name
        totalDataSent
        throughput
      }
      destinations {
        id
        totalDataSent
        throughput
      }
    }
  }`,
		},
	},
}

// GET_NAMESPACE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_NAMESPACE = Operation{
	Name: "GET_NAMESPACE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetNamespace($namespaceName: String!) {
    computePlatform {
      k8sActualNamespace(name: $namespaceName) {
        name
        selected
        dataStreamNames
        sources {
          namespace
          kind
          name
          dataStreamNames
          selected
          numberOfInstances
        }
      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetNamespace($namespaceName: String!) {
    computePlatform {
      k8sActualNamespace(name: $namespaceName) {
        name
        selected
        dataStreamNames
        sources {
          namespace
          kind
          name
          dataStreamNames
          selected
          numberOfInstances
        }
      }
    }
  }`,
		},
	},
}

// GET_NAMESPACES is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_NAMESPACES = Operation{
	Name: "GET_NAMESPACES",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetNamespaces {
    computePlatform {
      k8sActualNamespaces {
        name
        selected
        dataStreamNames
      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetNamespaces {
    computePlatform {
      k8sActualNamespaces {
        name
        selected
        dataStreamNames
      }
    }
  }`,
		},
	},
}

// GET_NAMESPACES_WITH_WORKLOADS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_NAMESPACES_WITH_WORKLOADS = Operation{
	Name: "GET_NAMESPACES_WITH_WORKLOADS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetNamespacesWithWorkloads {
    namespaces {
      name
      markedForInstrumentation
      dataStreamNames
      workloads {
        id {
          namespace
          kind
          name
        }
        markedForInstrumentation {
          markedForInstrumentation
        }
        dataStreamNames
        numberOfInstances
      }
    }
  }`,
		},
	},
}

// GET_NODE_COLLECTOR_INFO is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_NODE_COLLECTOR_INFO = Operation{
	Name: "GET_NODE_COLLECTOR_INFO",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query OdigletDaemonSetInfo {
    odigletDaemonSetInfo {
      status
      nodes {
        desired
        ready
      }
      resources {
        requests {
          cpu
          memory
        }
        limits {
          cpu
          memory
        }
      }
      imageVersion
      lastRolloutAt
      rolloutInProgress
      manifestYAML
      configMapYAML
    }
  }`,
		},
	},
}

// GET_NODE_COLLECTOR_PODS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_NODE_COLLECTOR_PODS = Operation{
	Name: "GET_NODE_COLLECTOR_PODS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query OdigletPods {
    odigletPods {
      namespace
      name
      status
      restartsCount
      nodeName
      creationTimestamp
      image
      collectorMetrics {
        metricsAcceptedRps
        metricsDroppedRps
        exporterSuccessRps
        exporterFailedRps
        window
        lastScrape
      }
    }
  }`,
		},
	},
}

// GET_PEER_SOURCES is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_PEER_SOURCES = Operation{
	Name: "GET_PEER_SOURCES",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.21"): `query GetPeerSources($serviceName: String!) {
    peerSources(serviceName: $serviceName) {
      inbound {
        serviceName
        requests
        dateTime
      }
      outbound {
        serviceName
        requests
        dateTime
      }
    }
  }`,
		},
	},
}

// GET_POTENTIAL_DESTINATIONS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_POTENTIAL_DESTINATIONS = Operation{
	Name: "GET_POTENTIAL_DESTINATIONS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetPotentialDestinations {
    potentialDestinations {
      type
      fields
    }
  }`,
		},
	},
}

// GET_PROFILING_SLOTS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_PROFILING_SLOTS = Operation{
	Name: "GET_PROFILING_SLOTS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.25"): `query GetProfilingSlots {
    profilingSlots {
      activeKeys
      keysWithData
      totalBytesUsed
      slotMaxBytes
      maxSlots
      maxTotalBytesBudget
      slotTtlSeconds
    }
  }`,
		},
	},
}

// GET_SAMPLING_RULES is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_SAMPLING_RULES = Operation{
	Name: "GET_SAMPLING_RULES",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.24"): `query GetSamplingRules {
    sampling {
      configs {
        effective {
          k8sHealthProbesSampling {
            enabled
            keepPercentage
          }
        }
      }
      rules {
        id
        name
        noisyOperations { ruleId
  name
  disabled
  sourceScopes { sources { namespace kind name }
  namespaces
  languages }
  operation {
    httpServer { route routePrefix method }
    httpClient { serverAddress templatedPath templatedPathPrefix method }
  }
  percentageAtMost
  notes }
        highlyRelevantOperations { ruleId
  name
  disabled
  sourceScopes { sources { namespace kind name }
  namespaces
  languages }
  error
  durationAtLeastMs
  operation {
    httpServer { route routePrefix method }
    kafkaConsumer { kafkaTopic }
    kafkaProducer { kafkaTopic }
  }
  percentageAtLeast
  notes }
        costReductionRules { ruleId
  name
  disabled
  sourceScopes { sources { namespace kind name }
  namespaces
  languages }
  operation {
    httpServer { route routePrefix method }
    kafkaConsumer { kafkaTopic }
    kafkaProducer { kafkaTopic }
  }
  percentageAtMost
  notes }
      }
    }
  }`,
		},
	},
}

// GET_SERVICE_MAP is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_SERVICE_MAP = Operation{
	Name: "GET_SERVICE_MAP",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.22"): `query GetServiceMap {
    getServiceMap {
      services {
        nodeId
        serviceName
        services {
          nodeId
          isVirtual
          serviceName
          requests
          dateTime
        }
      }
    }
  }`,
		},
	},
}

// GET_SOURCE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_SOURCE = Operation{
	Name: "GET_SOURCE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetSource($sourceId: K8sSourceId!) {
    computePlatform {
      source(sourceId: $sourceId) {
        namespace
        name
        kind
        dataStreamNames
        selected
        otelServiceName
        containers {
          containerName
          language
          runtimeVersion
          overriden
          instrumented
          instrumentationMessage
          otelDistroName
        }
        conditions {
          status
          type
          reason
          message

        }
        manifestYAML
        instrumentationConfigYAML
      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetSource($sourceId: K8sSourceId!) {
    computePlatform {
      source(sourceId: $sourceId) {
        namespace
        name
        kind
        dataStreamNames
        selected
        otelServiceName
        containers {
          containerName
          language
          runtimeVersion
          overriden
          instrumented
          instrumentationMessage
          otelDistroName
        }
        conditions {
          status
          type
          reason
          message

        }
        workloadOdigosHealthStatus {
          status
          reasonEnum
          message
        }
      }
    }
  }`,
		},
	},
}

// GET_SOURCES is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_SOURCES = Operation{
	Name: "GET_SOURCES",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetSources {
    computePlatform {
      sources {
        namespace
        name
        kind
        dataStreamNames
        selected
        otelServiceName
        containers {
          containerName
          language
          runtimeVersion
          overriden
          instrumented
          instrumentationMessage
          otelDistroName
        }
        conditions {
          status
          type
          reason
          message

        }
      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetSources {
    computePlatform {
      sources {
        namespace
        name
        kind
        dataStreamNames
        selected
        otelServiceName
        containers {
          containerName
          language
          runtimeVersion
          overriden
          instrumented
          instrumentationMessage
          otelDistroName
        }
        conditions {
          status
          type
          reason
          message

        }
      }
    }
  }`,
		},
	},
}

// GET_SOURCE_CONDITIONS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_SOURCE_CONDITIONS = Operation{
	Name: "GET_SOURCE_CONDITIONS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetSourceConditions {
    sourceConditions {
      namespace
      name
      kind
      conditions {
        status
        type
        reason
        message

      }
    }
  }`,
		},
	},
}

// GET_SOURCE_LIBRARIES is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_SOURCE_LIBRARIES = Operation{
	Name: "GET_SOURCE_LIBRARIES",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetSourceLibraries($namespace: String!, $kind: String!, $name: String!) {
    instrumentationInstanceComponents(namespace: $namespace, kind: $kind, name: $name) {
      name
      nonIdentifyingAttributes {
        key
        value
      }
    }
  }`,
		},
	},
}

// GET_SOURCE_PROFILING is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_SOURCE_PROFILING = Operation{
	Name: "GET_SOURCE_PROFILING",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.25"): `query GetSourceProfiling($sourceId: K8sSourceId!) {
    computePlatform {
      source(sourceId: $sourceId) {
        profiling {
          profileJson
        }
      }
    }
  }`,
		},
	},
}

// GET_TOKENS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_TOKENS = Operation{
	Name: "GET_TOKENS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `query GetTokens {
    computePlatform {
      apiTokens {
        token
        name
        issuedAt
        expiresAt
        message
      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `query GetTokens {
    computePlatform {
      apiTokens {
        token
        name
        issuedAt
        expiresAt
      }
    }
  }`,
		},
	},
}

// GET_WORKLOADS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_WORKLOADS = Operation{
	Name: "GET_WORKLOADS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.24"): `query GetWorkloads($filter: WorkloadFilter) {
    workloads(filter: $filter) {
      id {
    namespace
    kind
    name
  }
  serviceName
  dataStreamNames
  runtimeInfo {
    detectedLanguages
  }
  workloadOdigosHealthStatus {
    name
    status
    reasonEnum
    message
  }
  podsAgentInjectionStatus {
    name
    status
    reasonEnum
    message
  }
    }
  }`,
			version.MustParse("v1.20"): `query GetWorkloads($filter: WorkloadFilter) {
    workloads(filter: $filter) {
id {
        namespace
        kind
        name
      }
      serviceName
      dataStreamNames
      numberOfInstances
      markedForInstrumentation {
        markedForInstrumentation
      }
      runtimeInfo {
        detectedLanguages
      }
      containers {
        containerName
        runtimeInfo {
          language
          runtimeVersion
        }
        agentEnabled {
          agentEnabled
          agentEnabledStatus {
            status
            reasonEnum
            message
          }
          otelDistroName
        }
        overrides {
          containerName
          runtimeInfo {
            language
            runtimeVersion
          }
        }
      }
      conditions {
        runtimeDetection {
          name
          status
          reasonEnum
          message
        }
        agentInjectionEnabled {
          name
          status
          reasonEnum
          message
        }
        rollout {
          name
          status
          reasonEnum
          message
        }
        agentInjected {
          name
          status
          reasonEnum
          message
        }
        processesAgentHealth {
          name
          status
          reasonEnum
          message
        }
        expectingTelemetry {
          name
          status
          reasonEnum
          message
        }
      }
      workloadOdigosHealthStatus {
        name
        status
        reasonEnum
        message
      }
      podsAgentInjectionStatus {
        name
        status
        reasonEnum
        message
      }
      rollbackOccurred
    }
  }`,
		},
	},
}

// GET_WORKLOADS_BY_IDS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_WORKLOADS_BY_IDS = Operation{
	Name: "GET_WORKLOADS_BY_IDS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.30"): `query GetWorkloadsByIds($ids: [K8sWorkloadIdInput!]!) {
    workloadsByIds(ids: $ids) {
      id {
        namespace
        kind
        name
      }
      serviceName
      dataStreamNames
      numberOfInstances
      rollbackOccurred
      workloadOdigosHealthStatus {
        name
        status
        reasonEnum
        message
      }
      podsAgentInjectionStatus {
        name
        status
        reasonEnum
        message
      }
      podsOdigosHealthStatus {
        name
        status
        reasonEnum
        message
      }
      markedForInstrumentation {
        markedForInstrumentation
      }
      conditions {
        runtimeDetection {
          name
          status
          reasonEnum
          message
        }
        agentInjectionEnabled {
          name
          status
          reasonEnum
          message
        }
        rollout {
          name
          status
          reasonEnum
          message
        }
        autoRollback {
          name
          status
          reasonEnum
          message
        }
        agentInjected {
          name
          status
          reasonEnum
          message
        }
        processesAgentHealth {
          name
          status
          reasonEnum
          message
        }
        expectingTelemetry {
          name
          status
          reasonEnum
          message
        }
      }
      autoRollback {
        autoRollbackStatus {
          name
          status
          reasonEnum
          message
        }
        rollbackOccurred
      }
      runtimeInfo {
        detectedLanguages
      }
      containers {
        containerName
        runtimeInfo {
          language
          runtimeVersion
        }
        agentEnabled {
          agentEnabled
          agentEnabledStatus {
            status
            reasonEnum
            message
          }
          otelDistroName
        }
        overrides {
          containerName
          otelDistroName
          runtimeInfo {
            language
            runtimeVersion
          }
        }
        agentConfig {
          traces {
            headSampling {
              dryRun
              spanMetricsMode
              noisyOperations {
                ruleId
                name
                disabled
                operation {
                  httpServer {
                    route
                    routePrefix
                    method
                  }
                  httpClient {
                    serverAddress
                    templatedPath
                    templatedPathPrefix
                    method
                  }
                }
                percentageAtMost
              }
            }
          }
        }
        collectorConfig {
          tailSampling {
            noisyOperations {
              ruleId
              name
              disabled
              operation {
                httpServer {
                  route
                  routePrefix
                  method
                }
                httpClient {
                  serverAddress
                  templatedPath
                  templatedPathPrefix
                  method
                }
              }
              percentageAtMost
            }
            highlyRelevantOperations {
              ruleId
              name
              disabled
              error
              durationAtLeastMs
              operation {
                httpServer {
                  route
                  routePrefix
                  method
                }
                kafkaConsumer {
                  kafkaTopic
                }
                kafkaProducer {
                  kafkaTopic
                }
              }
              percentageAtLeast
            }
            costReductionRules {
              ruleId
              name
              disabled
              operation {
                httpServer {
                  route
                  routePrefix
                  method
                }
                kafkaConsumer {
                  kafkaTopic
                }
                kafkaProducer {
                  kafkaTopic
                }
              }
              percentageAtMost
            }
          }
        }
      }
      pods {
        podName
        nodeName
        startTime
        agentInjected
        agentInjectedStatus {
          name
          status
          reasonEnum
          message
        }
        k8sHealthStatus {
          name
          status
          reasonEnum
          message
        }
        odigosHealthStatus {
          name
          status
          reasonEnum
          message
        }
        containers {
          containerName
          otelDistroName
          started
          ready
          isCrashLoop
          restartCount
          runningStartedTime
          waitingReasonEnum
          waitingMessage
          k8sHealthStatus {
            name
            status
            reasonEnum
            message
          }
          odigosHealthStatus {
            name
            status
            reasonEnum
            message
          }
          processes {
            healthy
            healthStatus {
              name
              status
              reasonEnum
              message
            }
            identifyingAttributes {
              name
              value
            }
            instrumentations {
              name
              healthy
              message
              isStandardLibrary
            }
          }
        }
      }
      telemetryMetrics {
        throughputBytes
      }
    }
  }`,
			version.MustParse("v1.20"): `query GetWorkloadsByIds($ids: [K8sWorkloadIdInput!]!) {
    workloadsByIds(ids: $ids) {
id {
        namespace
        kind
        name
      }
      serviceName
      dataStreamNames
      numberOfInstances
      markedForInstrumentation {
        markedForInstrumentation
      }
      runtimeInfo {
        detectedLanguages
      }
      containers {
        containerName
        runtimeInfo {
          language
          runtimeVersion
        }
        agentEnabled {
          agentEnabled
          agentEnabledStatus {
            status
            reasonEnum
            message
          }
          otelDistroName
        }
        overrides {
          containerName
          runtimeInfo {
            language
            runtimeVersion
          }
        }
      }
      conditions {
        runtimeDetection {
          name
          status
          reasonEnum
          message
        }
        agentInjectionEnabled {
          name
          status
          reasonEnum
          message
        }
        rollout {
          name
          status
          reasonEnum
          message
        }
        agentInjected {
          name
          status
          reasonEnum
          message
        }
        processesAgentHealth {
          name
          status
          reasonEnum
          message
        }
        expectingTelemetry {
          name
          status
          reasonEnum
          message
        }
      }
      workloadOdigosHealthStatus {
        name
        status
        reasonEnum
        message
      }
      podsAgentInjectionStatus {
        name
        status
        reasonEnum
        message
      }
      rollbackOccurred
    }
  }`,
		},
	},
}

// GET_WORKLOADS_BY_IDS_SLIM is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var GET_WORKLOADS_BY_IDS_SLIM = Operation{
	Name: "GET_WORKLOADS_BY_IDS_SLIM",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.24"): `query GetWorkloadsByIdsSlim($ids: [K8sWorkloadIdInput!]!) {
    workloadsByIds(ids: $ids) {
      id {
    namespace
    kind
    name
  }
  serviceName
  dataStreamNames
  runtimeInfo {
    detectedLanguages
  }
  workloadOdigosHealthStatus {
    name
    status
    reasonEnum
    message
  }
  podsAgentInjectionStatus {
    name
    status
    reasonEnum
    message
  }
    }
  }`,
			version.MustParse("v1.20"): `query GetWorkloadsByIdsSlim($ids: [K8sWorkloadIdInput!]!) {
    workloadsByIds(ids: $ids) {
      id {
        namespace
        kind
        name
      }
      serviceName
      dataStreamNames
      numberOfInstances
      markedForInstrumentation {
        markedForInstrumentation
      }
      runtimeInfo {
        detectedLanguages
      }
      containers {
        containerName
        runtimeInfo {
          language
          runtimeVersion
        }
        agentEnabled {
          agentEnabled
          agentEnabledStatus {
            status
            reasonEnum
            message
          }
          otelDistroName
        }
        overrides {
          containerName
          runtimeInfo {
            language
            runtimeVersion
          }
        }
      }
      conditions {
        runtimeDetection {
          name
          status
          reasonEnum
          message
        }
        agentInjectionEnabled {
          name
          status
          reasonEnum
          message
        }
        rollout {
          name
          status
          reasonEnum
          message
        }
        agentInjected {
          name
          status
          reasonEnum
          message
        }
        processesAgentHealth {
          name
          status
          reasonEnum
          message
        }
        expectingTelemetry {
          name
          status
          reasonEnum
          message
        }
      }
      workloadOdigosHealthStatus {
        name
        status
        reasonEnum
        message
      }
      podsAgentInjectionStatus {
        name
        status
        reasonEnum
        message
      }
      rollbackOccurred
    }
  }`,
		},
	},
}

// AllRemoteQueries is the registry of remote operations declared in this
// file. Compatibility-matrix tests iterate over it to assert version-floor
// invariants across the entire generated surface.
var AllRemoteQueries = []*Operation{
	&GET_ACTIONS,
	&GET_COLLECTOR_POD_INFO,
	&GET_CONFIG,
	&GET_CONFIG_YAMLS,
	&GET_DATA_STREAMS,
	&GET_DESCRIBE_ODIGOS,
	&GET_DESCRIBE_SOURCE,
	&GET_DESTINATIONS,
	&GET_DESTINATION_CATEGORIES,
	&GET_EFFECTIVE_CONFIG,
	&GET_GATEWAY_INFO,
	&GET_GATEWAY_PODS,
	&GET_INSTRUMENTATION_RULES,
	&GET_K8S_MANIFEST,
	&GET_METRICS,
	&GET_NAMESPACE,
	&GET_NAMESPACES,
	&GET_NAMESPACES_WITH_WORKLOADS,
	&GET_NODE_COLLECTOR_INFO,
	&GET_NODE_COLLECTOR_PODS,
	&GET_PEER_SOURCES,
	&GET_POTENTIAL_DESTINATIONS,
	&GET_PROFILING_SLOTS,
	&GET_SAMPLING_RULES,
	&GET_SERVICE_MAP,
	&GET_SOURCE,
	&GET_SOURCES,
	&GET_SOURCE_CONDITIONS,
	&GET_SOURCE_LIBRARIES,
	&GET_SOURCE_PROFILING,
	&GET_TOKENS,
	&GET_WORKLOADS,
	&GET_WORKLOADS_BY_IDS,
	&GET_WORKLOADS_BY_IDS_SLIM,
}
