// Code generated by tools/gen-graphql. DO NOT EDIT.
//
// Source: central-ui/src/graphql/{queries,mutations}/**/*.ts
// Regenerate with: go generate ./operations

package operations

import (
	"github.com/odigos-io/odigos-central-client/platform"
	"github.com/odigos-io/odigos-central-client/version"
)

// CREATE_ACTION is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var CREATE_ACTION = Operation{
	Name: "CREATE_ACTION",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.33"): `mutation CreateAction($action: ActionInput!) {
    createAction(action: $action) {
      id
      type
      name
      notes
      disabled
      signals
      fields {
        collectContainerAttributes
        collectReplicaSetAttributes
        collectWorkloadId
        collectClusterId
        labelsAttributes {
          labelKey
          attributeKey
          from
          fromSources
        }
        annotationsAttributes {
          annotationKey
          attributeKey
          from
          fromSources
        }
        clusterAttributes {
          attributeName
          attributeStringValue
        }
        overwriteExistingValues
        attributeNamesToDelete
        renames
        piiCategories
        customFormatMaskings {
          lookupKey
          dataFormat
        }
        customRegexMaskings {
          regex
        }
        extractAttribute {
          extractions {
            targetAttributeName
            lookupKey
            dataFormat
            regex
          }
        }
        urlTemplatizationRulesGroups {
          filterK8sNamespace
          filterK8sWorkloadKind
          filterK8sWorkloadName
          filterProgrammingLanguage
          notes
          workloadFilters {
            kind
            name
          }
          templatizationRules {
            template
            notes
            examples
          }
        }
      }
      conditions {
        status
        type
        reason
        message
      }
    }
  }`,
			version.MustParse("v1.29"): `mutation CreateAction($action: ActionInput!) {
    createAction(action: $action) {
      id
      type
      name
      notes
      disabled
      signals
      fields {
        collectContainerAttributes
        collectReplicaSetAttributes
        collectWorkloadId
        collectClusterId
        labelsAttributes {
          labelKey
          attributeKey
          from
          fromSources
        }
        annotationsAttributes {
          annotationKey
          attributeKey
          from
          fromSources
        }
        clusterAttributes {
          attributeName
          attributeStringValue
        }
        overwriteExistingValues
        attributeNamesToDelete
        renames
        piiCategories
        extractAttribute {
          extractions {
            targetAttributeName
            lookupKey
            dataFormat
            regex
          }
        }
        urlTemplatizationRulesGroups {
          filterK8sNamespace
          filterK8sWorkloadKind
          filterK8sWorkloadName
          filterProgrammingLanguage
          notes
          workloadFilters {
            kind
            name
          }
          templatizationRules {
            template
            notes
            examples
          }
        }
      }
      conditions {
        status
        type
        reason
        message
      }
    }
  }`,
			version.MustParse("v1.28"): `mutation CreateAction($action: ActionInput!) {
    createAction(action: $action) {
      id
      type
      name
      notes
      disabled
      signals
      fields {
        collectContainerAttributes
        collectReplicaSetAttributes
        collectWorkloadId
        collectClusterId
        labelsAttributes {
          labelKey
          attributeKey
          from
          fromSources
        }
        annotationsAttributes {
          annotationKey
          attributeKey
          from
          fromSources
        }
        clusterAttributes {
          attributeName
          attributeStringValue
        }
        overwriteExistingValues
        attributeNamesToDelete
        renames
        piiCategories
        urlTemplatizationRulesGroups {
          filterK8sNamespace
          filterK8sWorkloadKind
          filterK8sWorkloadName
          filterProgrammingLanguage
          notes
          workloadFilters {
            kind
            name
          }
          templatizationRules {
            template
            notes
            examples
          }
        }
      }
      conditions {
        status
        type
        reason
        message
      }
    }
  }`,
			version.MustParse("v1.20"): `mutation CreateAction($action: ActionInput!) {
    createAction(action: $action) {
      id
      type
      name
      notes
      disabled
      signals
      fields {
        collectContainerAttributes
        collectReplicaSetAttributes
        collectWorkloadId
        collectClusterId
        labelsAttributes {
          labelKey
          attributeKey
          from
          fromSources
        }
        annotationsAttributes {
          annotationKey
          attributeKey
          from
          fromSources
        }
        clusterAttributes {
          attributeName
          attributeStringValue
        }
        overwriteExistingValues
        attributeNamesToDelete
        renames
        piiCategories
        samplingPercentage
        fallbackSamplingRatio
        endpointsFilters {
          httpRoute
          serviceName
          minimumLatencyThreshold
          fallbackSamplingRatio
        }
        servicesNameFilters {
          serviceName
          samplingRatio
          fallbackSamplingRatio
        }
        attributeFilters {
          serviceName
          attributeKey
          fallbackSamplingRatio
          condition {
            stringCondition {
              operation
              expectedValue
            }
          }
        }
      }
      conditions {
        status
        type
        reason
        message

      }
    }
  }`,
		},
	},
}

// CREATE_COST_REDUCTION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var CREATE_COST_REDUCTION_RULE = Operation{
	Name: "CREATE_COST_REDUCTION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.26"): `mutation CreateCostReductionRule($samplingId: ID!, $rule: CostReductionRuleInput!) {
    createCostReductionRule(samplingId: $samplingId, rule: $rule) {
      ruleId
      name
      disabled
      sourceScopes {
        sources { namespace kind name }
        namespaces
        languages
      }
      operation {
        httpServer { route routePrefix method }
        kafkaConsumer { kafkaTopic }
        kafkaProducer { kafkaTopic }
      }
      percentageAtMost
      notes
    }
  }`,
		},
	},
}

// CREATE_DESTINATION is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var CREATE_DESTINATION = Operation{
	Name: "CREATE_DESTINATION",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation CreateNewDestination($destination: DestinationInput!) {
    createNewDestination(destination: $destination) {
      id
      name
      disabled
      dataStreamNames
      fields
      exportedSignals {
        logs
        metrics
        traces
      }
      destinationType {
        type
        imageUrl
        displayName
        supportedSignals {
          logs {
            supported
          }
          metrics {
            supported
          }
          traces {
            supported
          }
        }
      }
      conditions {
        status
        type
        reason
        message

      }
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `mutation CreateNewDestination($destination: DestinationInput!) {
    createNewDestination(destination: $destination) {
      id
      name
      disabled
      dataStreamNames
      fields
      exportedSignals {
        logs
        metrics
        traces
      }
      destinationType {
        type
        imageUrl
        displayName
        supportedSignals {
          logs {
            supported
          }
          metrics {
            supported
          }
          traces {
            supported
          }
        }
      }
      conditions
    }
  }`,
		},
	},
}

// CREATE_HIGHLY_RELEVANT_OPERATION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var CREATE_HIGHLY_RELEVANT_OPERATION_RULE = Operation{
	Name: "CREATE_HIGHLY_RELEVANT_OPERATION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.26"): `mutation CreateHighlyRelevantOperationRule($samplingId: ID!, $rule: HighlyRelevantOperationRuleInput!) {
    createHighlyRelevantOperationRule(samplingId: $samplingId, rule: $rule) {
      ruleId
      name
      disabled
      sourceScopes {
        sources { namespace kind name }
        namespaces
        languages
      }
      error
      durationAtLeastMs
      operation {
        httpServer { route routePrefix method }
        kafkaConsumer { kafkaTopic }
        kafkaProducer { kafkaTopic }
      }
      percentageAtLeast
      notes
    }
  }`,
		},
	},
}

// CREATE_INSTRUMENTATION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var CREATE_INSTRUMENTATION_RULE = Operation{
	Name: "CREATE_INSTRUMENTATION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.33"): `mutation CreateInstrumentationRule($instrumentationRule: InstrumentationRuleInput!) {
    createInstrumentationRule(instrumentationRule: $instrumentationRule) {
      type
      ruleId
      ruleName
      notes
      disabled
      mutable
      profileName
      sourcesScopes { sources { namespace kind name }
  namespaces
  languages }
      payloadCollection {
        httpRequest {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        httpResponse {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        dbQuery {
          maxPayloadLength
          dropPartialPayloads
        }
        messaging {
          maxPayloadLength
          dropPartialPayloads
        }
      }
      codeAttributes {
        column
        filePath
        function
        lineNumber
        namespace
        stacktrace
      }
      headersCollection {
        headerKeys
      }
      customInstrumentations {
        golang {
          packageName
          functionName
          receiverName
          receiverMethodName
        }
        java {
          methodName
          className
        }
        php {
          className
          functionName
        }
      }
    }
  }`,
			version.MustParse("v1.26"): `mutation CreateInstrumentationRule($instrumentationRule: InstrumentationRuleInput!) {
    createInstrumentationRule(instrumentationRule: $instrumentationRule) {
      type
      ruleId
      ruleName
      notes
      disabled
      mutable
      profileName
      sourcesScopes { sources { namespace kind name }
  namespaces
  languages }
      payloadCollection {
        httpRequest {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        httpResponse {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        dbQuery {
          maxPayloadLength
          dropPartialPayloads
        }
        messaging {
          maxPayloadLength
          dropPartialPayloads
        }
      }
      codeAttributes {
        column
        filePath
        function
        lineNumber
        namespace
        stacktrace
      }
      headersCollection {
        headerKeys
      }
      customInstrumentations {
        golang {
          packageName
          functionName
          receiverName
          receiverMethodName
        }
        java {
          methodName
          className
        }
      }
    }
  }`,
			version.MustParse("v1.20"): `mutation CreateInstrumentationRule($instrumentationRule: InstrumentationRuleInput!) {
    createInstrumentationRule(instrumentationRule: $instrumentationRule) {
      type
      ruleId
      ruleName
      notes
      disabled
      mutable
      profileName
      # Echoed back so a later edit doesn't clear scope (update is a full replace).
      workloads {
        namespace
        kind
        name
      }
      payloadCollection {
        httpRequest {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        httpResponse {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        dbQuery {
          maxPayloadLength
          dropPartialPayloads
        }
        messaging {
          maxPayloadLength
          dropPartialPayloads
        }
      }
      codeAttributes {
        column
        filePath
        function
        lineNumber
        namespace
        stacktrace
      }
      headersCollection {
        headerKeys
      }
      customInstrumentations {
        golang {
          packageName
          functionName
          receiverName
          receiverMethodName
        }
        java {
          methodName
          className
        }
      }
    }
  }`,
		},
	},
}

// CREATE_NOISY_OPERATION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var CREATE_NOISY_OPERATION_RULE = Operation{
	Name: "CREATE_NOISY_OPERATION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.32"): `mutation CreateNoisyOperationRule($samplingId: ID!, $rule: NoisyOperationRuleInput!) {
    createNoisyOperationRule(samplingId: $samplingId, rule: $rule) {
      ruleId
      name
      disabled
      sourceScopes {
        sources { namespace kind name }
        namespaces
        languages
      }
      operation {
        httpServer { route routePrefix method queryParams { name valueExact } }
        httpClient { serverAddress templatedPath templatedPathPrefix method }
      }
      percentageAtMost
      notes
    }
  }`,
			version.MustParse("v1.26"): `mutation CreateNoisyOperationRule($samplingId: ID!, $rule: NoisyOperationRuleInput!) {
    createNoisyOperationRule(samplingId: $samplingId, rule: $rule) {
      ruleId
      name
      disabled
      sourceScopes {
        sources { namespace kind name }
        namespaces
        languages
      }
      operation {
        httpServer { route routePrefix method }
        httpClient { serverAddress templatedPath templatedPathPrefix method }
      }
      percentageAtMost
      notes
    }
  }`,
		},
	},
}

// DELETE_ACTION is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var DELETE_ACTION = Operation{
	Name: "DELETE_ACTION",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation DeleteAction($id: ID!, $actionType: String!) {
    deleteAction(id: $id, actionType: $actionType)
  }`,
		},
	},
}

// DELETE_COST_REDUCTION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var DELETE_COST_REDUCTION_RULE = Operation{
	Name: "DELETE_COST_REDUCTION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.24"): `mutation DeleteCostReductionRule($samplingId: ID!, $ruleId: ID!) {
    deleteCostReductionRule(samplingId: $samplingId, ruleId: $ruleId)
  }`,
		},
	},
}

// DELETE_DATA_STREAM is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var DELETE_DATA_STREAM = Operation{
	Name: "DELETE_DATA_STREAM",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation DeleteDataStream($id: ID!) {
    deleteDataStream(id: $id)
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `mutation DeleteDataStream($id: ID!) {
    deleteDataStream(id: $id)
  }`,
		},
	},
}

// DELETE_DESTINATION is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var DELETE_DESTINATION = Operation{
	Name: "DELETE_DESTINATION",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation DeleteDestination($id: ID!, $currentStreamName: String!) {
    deleteDestination(id: $id, currentStreamName: $currentStreamName)
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `mutation DeleteDestination($id: ID!, $currentStreamName: String!) {
    deleteDestination(id: $id, currentStreamName: $currentStreamName)
  }`,
		},
	},
}

// DELETE_HIGHLY_RELEVANT_OPERATION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var DELETE_HIGHLY_RELEVANT_OPERATION_RULE = Operation{
	Name: "DELETE_HIGHLY_RELEVANT_OPERATION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.24"): `mutation DeleteHighlyRelevantOperationRule($samplingId: ID!, $ruleId: ID!) {
    deleteHighlyRelevantOperationRule(samplingId: $samplingId, ruleId: $ruleId)
  }`,
		},
	},
}

// DELETE_INSTURMENTATION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var DELETE_INSTURMENTATION_RULE = Operation{
	Name: "DELETE_INSTURMENTATION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation DeleteInstrumentationRule($ruleId: ID!) {
    deleteInstrumentationRule(ruleId: $ruleId)
  }`,
		},
	},
}

// DELETE_NOISY_OPERATION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var DELETE_NOISY_OPERATION_RULE = Operation{
	Name: "DELETE_NOISY_OPERATION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.24"): `mutation DeleteNoisyOperationRule($samplingId: ID!, $ruleId: ID!) {
    deleteNoisyOperationRule(samplingId: $samplingId, ruleId: $ruleId)
  }`,
		},
	},
}

// ENABLE_SOURCE_PROFILING is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var ENABLE_SOURCE_PROFILING = Operation{
	Name: "ENABLE_SOURCE_PROFILING",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.25"): `mutation EnableSourceProfiling($namespace: String!, $kind: String!, $name: String!) {
    enableSourceProfiling(namespace: $namespace, kind: $kind, name: $name) {
      status
      sourceKey
      maxSlots
      activeSlots
    }
  }`,
		},
	},
}

// PERSIST_NAMESPACES is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var PERSIST_NAMESPACES = Operation{
	Name: "PERSIST_NAMESPACES",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation PersistNamespaces($namespaces: [PersistNamespaceItemInput!]!) {
    persistK8sNamespaces(namespaces: $namespaces)
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `mutation PersistNamespaces($namespaces: [PersistNamespaceItemInput!]!) {
    persistVmNamespaces(namespaces: $namespaces)
  }`,
		},
	},
}

// PERSIST_SOURCES is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var PERSIST_SOURCES = Operation{
	Name: "PERSIST_SOURCES",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation PersistSources($sources: [PersistNamespaceSourceInput!]!) {
    persistK8sSources(sources: $sources)
  }`,
		},
	},
}

// RECOVER_FROM_ROLLBACK is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var RECOVER_FROM_ROLLBACK = Operation{
	Name: "RECOVER_FROM_ROLLBACK",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation RecoverFromRollbackForWorkload($sourceId: K8sSourceId!) {
    recoverFromRollbackForWorkload(sourceId: $sourceId)
  }`,
		},
	},
}

// RESET_LOCAL_UI_CONFIG_TO_FACTORY_DEFAULTS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var RESET_LOCAL_UI_CONFIG_TO_FACTORY_DEFAULTS = Operation{
	Name: "RESET_LOCAL_UI_CONFIG_TO_FACTORY_DEFAULTS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.24"): `mutation ResetLocalUiConfigToFactoryDefaults {
    resetLocalUiConfigToFactoryDefaults
  }`,
		},
	},
}

// RESTART_POD is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var RESTART_POD = Operation{
	Name: "RESTART_POD",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation RestartPod($namespace: String!, $name: String!) {
    restartPod(namespace: $namespace, name: $name)
  }`,
		},
	},
}

// RESTART_WORKLOADS is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var RESTART_WORKLOADS = Operation{
	Name: "RESTART_WORKLOADS",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation RestartWorkloads($sourceIds: [K8sSourceId!]!) {
    restartWorkloads(sourceIds: $sourceIds)
  }`,
		},
	},
}

// TEST_DESTINATION_CONNECTION is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var TEST_DESTINATION_CONNECTION = Operation{
	Name: "TEST_DESTINATION_CONNECTION",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation TestConnection($destination: DestinationInput!) {
    testConnectionForDestination(destination: $destination) {
      succeeded
      statusCode
      destinationType
      message
      reason
    }
  }`,
		},
	},
}

// UPDATE_ACTION is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_ACTION = Operation{
	Name: "UPDATE_ACTION",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.33"): `mutation UpdateAction($id: ID!, $action: ActionInput!) {
    updateAction(id: $id, action: $action) {
      id
      type
      name
      notes
      disabled
      signals
      fields {
        collectContainerAttributes
        collectReplicaSetAttributes
        collectWorkloadId
        collectClusterId
        labelsAttributes {
          labelKey
          attributeKey
          from
          fromSources
        }
        annotationsAttributes {
          annotationKey
          attributeKey
          from
          fromSources
        }
        clusterAttributes {
          attributeName
          attributeStringValue
        }
        overwriteExistingValues
        attributeNamesToDelete
        renames
        piiCategories
        customFormatMaskings {
          lookupKey
          dataFormat
        }
        customRegexMaskings {
          regex
        }
        extractAttribute {
          extractions {
            targetAttributeName
            lookupKey
            dataFormat
            regex
          }
        }
        urlTemplatizationRulesGroups {
          filterK8sNamespace
          filterK8sWorkloadKind
          filterK8sWorkloadName
          filterProgrammingLanguage
          notes
          workloadFilters {
            kind
            name
          }
          templatizationRules {
            template
            notes
            examples
          }
        }
      }
      conditions {
        status
        type
        reason
        message
      }
    }
  }`,
			version.MustParse("v1.29"): `mutation UpdateAction($id: ID!, $action: ActionInput!) {
    updateAction(id: $id, action: $action) {
      id
      type
      name
      notes
      disabled
      signals
      fields {
        collectContainerAttributes
        collectReplicaSetAttributes
        collectWorkloadId
        collectClusterId
        labelsAttributes {
          labelKey
          attributeKey
          from
          fromSources
        }
        annotationsAttributes {
          annotationKey
          attributeKey
          from
          fromSources
        }
        clusterAttributes {
          attributeName
          attributeStringValue
        }
        overwriteExistingValues
        attributeNamesToDelete
        renames
        piiCategories
        extractAttribute {
          extractions {
            targetAttributeName
            lookupKey
            dataFormat
            regex
          }
        }
        urlTemplatizationRulesGroups {
          filterK8sNamespace
          filterK8sWorkloadKind
          filterK8sWorkloadName
          filterProgrammingLanguage
          notes
          workloadFilters {
            kind
            name
          }
          templatizationRules {
            template
            notes
            examples
          }
        }
      }
      conditions {
        status
        type
        reason
        message
      }
    }
  }`,
			version.MustParse("v1.28"): `mutation UpdateAction($id: ID!, $action: ActionInput!) {
    updateAction(id: $id, action: $action) {
      id
      type
      name
      notes
      disabled
      signals
      fields {
        collectContainerAttributes
        collectReplicaSetAttributes
        collectWorkloadId
        collectClusterId
        labelsAttributes {
          labelKey
          attributeKey
          from
          fromSources
        }
        annotationsAttributes {
          annotationKey
          attributeKey
          from
          fromSources
        }
        clusterAttributes {
          attributeName
          attributeStringValue
        }
        overwriteExistingValues
        attributeNamesToDelete
        renames
        piiCategories
        urlTemplatizationRulesGroups {
          filterK8sNamespace
          filterK8sWorkloadKind
          filterK8sWorkloadName
          filterProgrammingLanguage
          notes
          workloadFilters {
            kind
            name
          }
          templatizationRules {
            template
            notes
            examples
          }
        }
      }
      conditions {
        status
        type
        reason
        message
      }
    }
  }`,
			version.MustParse("v1.20"): `mutation UpdateAction($id: ID!, $action: ActionInput!) {
    updateAction(id: $id, action: $action) {
      id
      type
      name
      notes
      disabled
      signals
      fields {
        collectContainerAttributes
        collectReplicaSetAttributes
        collectWorkloadId
        collectClusterId
        labelsAttributes {
          labelKey
          attributeKey
          from
          fromSources
        }
        annotationsAttributes {
          annotationKey
          attributeKey
          from
          fromSources
        }
        clusterAttributes {
          attributeName
          attributeStringValue
        }
        overwriteExistingValues
        attributeNamesToDelete
        renames
        piiCategories
        samplingPercentage
        fallbackSamplingRatio
        endpointsFilters {
          httpRoute
          serviceName
          minimumLatencyThreshold
          fallbackSamplingRatio
        }
        servicesNameFilters {
          serviceName
          samplingRatio
          fallbackSamplingRatio
        }
        attributeFilters {
          serviceName
          attributeKey
          fallbackSamplingRatio
          condition {
            stringCondition {
              operation
              expectedValue
            }
          }
        }
      }
      conditions {
        status
        type
        reason
        message

      }
    }
  }`,
		},
	},
}

// UPDATE_COST_REDUCTION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_COST_REDUCTION_RULE = Operation{
	Name: "UPDATE_COST_REDUCTION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.26"): `mutation UpdateCostReductionRule($samplingId: ID!, $ruleId: ID!, $rule: CostReductionRuleInput!) {
    updateCostReductionRule(samplingId: $samplingId, ruleId: $ruleId, rule: $rule) {
      ruleId
      name
      disabled
      sourceScopes {
        sources { namespace kind name }
        namespaces
        languages
      }
      operation {
        httpServer { route routePrefix method }
        kafkaConsumer { kafkaTopic }
        kafkaProducer { kafkaTopic }
      }
      percentageAtMost
      notes
    }
  }`,
		},
	},
}

// UPDATE_DATA_STREAM is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_DATA_STREAM = Operation{
	Name: "UPDATE_DATA_STREAM",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation UpdateDataStream($id: ID!, $dataStream: DataStreamInput!) {
    updateDataStream(id: $id, dataStream: $dataStream) {
      name
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `mutation UpdateDataStream($id: ID!, $dataStream: DataStreamInput!) {
    updateDataStream(id: $id, dataStream: $dataStream) {
      name
    }
  }`,
		},
	},
}

// UPDATE_DESTINATION is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_DESTINATION = Operation{
	Name: "UPDATE_DESTINATION",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation UpdateDestination($id: ID!, $destination: DestinationInput!) {
    updateDestination(id: $id, destination: $destination) {
      id
    }
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `mutation UpdateDestination($id: ID!, $destination: DestinationInput!) {
    updateDestination(id: $id, destination: $destination) {
      id
    }
  }`,
		},
	},
}

// UPDATE_HIGHLY_RELEVANT_OPERATION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_HIGHLY_RELEVANT_OPERATION_RULE = Operation{
	Name: "UPDATE_HIGHLY_RELEVANT_OPERATION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.26"): `mutation UpdateHighlyRelevantOperationRule($samplingId: ID!, $ruleId: ID!, $rule: HighlyRelevantOperationRuleInput!) {
    updateHighlyRelevantOperationRule(samplingId: $samplingId, ruleId: $ruleId, rule: $rule) {
      ruleId
      name
      disabled
      sourceScopes {
        sources { namespace kind name }
        namespaces
        languages
      }
      error
      durationAtLeastMs
      operation {
        httpServer { route routePrefix method }
        kafkaConsumer { kafkaTopic }
        kafkaProducer { kafkaTopic }
      }
      percentageAtLeast
      notes
    }
  }`,
		},
	},
}

// UPDATE_INSTURMENTATION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_INSTURMENTATION_RULE = Operation{
	Name: "UPDATE_INSTURMENTATION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.33"): `mutation UpdateInstrumentationRule($ruleId: ID!, $instrumentationRule: InstrumentationRuleInput!) {
    updateInstrumentationRule(ruleId: $ruleId, instrumentationRule: $instrumentationRule) {
      type
      ruleId
      ruleName
      notes
      disabled
      mutable
      profileName
      sourcesScopes { sources { namespace kind name }
  namespaces
  languages }
      payloadCollection {
        httpRequest {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        httpResponse {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        dbQuery {
          maxPayloadLength
          dropPartialPayloads
        }
        messaging {
          maxPayloadLength
          dropPartialPayloads
        }
      }
      codeAttributes {
        column
        filePath
        function
        lineNumber
        namespace
        stacktrace
      }
      headersCollection {
        headerKeys
      }
      customInstrumentations {
        golang {
          packageName
          functionName
          receiverName
          receiverMethodName
        }
        java {
          methodName
          className
        }
        php {
          className
          functionName
        }
      }
    }
  }`,
			version.MustParse("v1.26"): `mutation UpdateInstrumentationRule($ruleId: ID!, $instrumentationRule: InstrumentationRuleInput!) {
    updateInstrumentationRule(ruleId: $ruleId, instrumentationRule: $instrumentationRule) {
      type
      ruleId
      ruleName
      notes
      disabled
      mutable
      profileName
      sourcesScopes { sources { namespace kind name }
  namespaces
  languages }
      payloadCollection {
        httpRequest {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        httpResponse {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        dbQuery {
          maxPayloadLength
          dropPartialPayloads
        }
        messaging {
          maxPayloadLength
          dropPartialPayloads
        }
      }
      codeAttributes {
        column
        filePath
        function
        lineNumber
        namespace
        stacktrace
      }
      headersCollection {
        headerKeys
      }
      customInstrumentations {
        golang {
          packageName
          functionName
          receiverName
          receiverMethodName
        }
        java {
          methodName
          className
        }
      }
    }
  }`,
			version.MustParse("v1.20"): `mutation UpdateInstrumentationRule($ruleId: ID!, $instrumentationRule: InstrumentationRuleInput!) {
    updateInstrumentationRule(ruleId: $ruleId, instrumentationRule: $instrumentationRule) {
      type
      ruleId
      ruleName
      notes
      disabled
      mutable
      profileName
      # Echoed back so a later edit doesn't clear scope (update is a full replace).
      workloads {
        namespace
        kind
        name
      }
      payloadCollection {
        httpRequest {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        httpResponse {
          mimeTypes
          maxPayloadLength
          dropPartialPayloads
        }
        dbQuery {
          maxPayloadLength
          dropPartialPayloads
        }
        messaging {
          maxPayloadLength
          dropPartialPayloads
        }
      }
      codeAttributes {
        column
        filePath
        function
        lineNumber
        namespace
        stacktrace
      }
      headersCollection {
        headerKeys
      }
      customInstrumentations {
        golang {
          packageName
          functionName
          receiverName
          receiverMethodName
        }
        java {
          methodName
          className
        }
      }
    }
  }`,
		},
	},
}

// UPDATE_LOCAL_UI_CONFIG is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_LOCAL_UI_CONFIG = Operation{
	Name: "UPDATE_LOCAL_UI_CONFIG",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.24"): `mutation UpdateLocalUiConfig($config: LocalUiConfigInput!) {
    updateLocalUiConfig(config: $config)
  }`,
		},
	},
}

// UPDATE_LOCAL_UI_SAMPLING_CONFIG is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_LOCAL_UI_SAMPLING_CONFIG = Operation{
	Name: "UPDATE_LOCAL_UI_SAMPLING_CONFIG",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.24"): `mutation UpdateLocalUiSamplingConfig($config: SamplingConfigInput) {
    updateLocalUiSamplingConfig(config: $config)
  }`,
		},
	},
}

// UPDATE_NOISY_OPERATION_RULE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_NOISY_OPERATION_RULE = Operation{
	Name: "UPDATE_NOISY_OPERATION_RULE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.32"): `mutation UpdateNoisyOperationRule($samplingId: ID!, $ruleId: ID!, $rule: NoisyOperationRuleInput!) {
    updateNoisyOperationRule(samplingId: $samplingId, ruleId: $ruleId, rule: $rule) {
      ruleId
      name
      disabled
      sourceScopes {
        sources { namespace kind name }
        namespaces
        languages
      }
      operation {
        httpServer { route routePrefix method queryParams { name valueExact } }
        httpClient { serverAddress templatedPath templatedPathPrefix method }
      }
      percentageAtMost
      notes
    }
  }`,
			version.MustParse("v1.26"): `mutation UpdateNoisyOperationRule($samplingId: ID!, $ruleId: ID!, $rule: NoisyOperationRuleInput!) {
    updateNoisyOperationRule(samplingId: $samplingId, ruleId: $ruleId, rule: $rule) {
      ruleId
      name
      disabled
      sourceScopes {
        sources { namespace kind name }
        namespaces
        languages
      }
      operation {
        httpServer { route routePrefix method }
        httpClient { serverAddress templatedPath templatedPathPrefix method }
      }
      percentageAtMost
      notes
    }
  }`,
		},
	},
}

// UPDATE_REMOTE_CONFIG is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_REMOTE_CONFIG = Operation{
	Name: "UPDATE_REMOTE_CONFIG",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation UpdateRemoteConfig($config: RemoteConfigInput!) {
    updateRemoteConfig(config: $config)
  }`,
		},
	},
}

// UPDATE_SOURCE is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_SOURCE = Operation{
	Name: "UPDATE_SOURCE",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation UpdateK8sActualSource($sourceId: K8sSourceId!, $patchSourceRequest: PatchSourceRequestInput!) {
    updateK8sActualSource(sourceId: $sourceId, patchSourceRequest: $patchSourceRequest)
  }`,
		},
	},
}

// UPDATE_TOKEN is a remote (cluster-scoped) GraphQL operation. Its document
// varies by proxy platform type and Odigos version; use Operation.Pick to
// select the right variant for a given proxy.
var UPDATE_TOKEN = Operation{
	Name: "UPDATE_TOKEN",
	Variants: map[platform.Type]map[version.Version]string{
		platform.K8s: {
			version.MustParse("v1.20"): `mutation UpdateApiToken($token: String!) {
    updateApiToken(token: $token)
  }`,
		},
		platform.Vm: {
			version.MustParse("v0.1"): `mutation UpdateApiToken($token: String!) {
    updateApiToken(token: $token)
  }`,
		},
	},
}

// AllRemoteMutations is the registry of remote operations declared in this
// file. Compatibility-matrix tests iterate over it to assert version-floor
// invariants across the entire generated surface.
var AllRemoteMutations = []*Operation{
	&CREATE_ACTION,
	&CREATE_COST_REDUCTION_RULE,
	&CREATE_DESTINATION,
	&CREATE_HIGHLY_RELEVANT_OPERATION_RULE,
	&CREATE_INSTRUMENTATION_RULE,
	&CREATE_NOISY_OPERATION_RULE,
	&DELETE_ACTION,
	&DELETE_COST_REDUCTION_RULE,
	&DELETE_DATA_STREAM,
	&DELETE_DESTINATION,
	&DELETE_HIGHLY_RELEVANT_OPERATION_RULE,
	&DELETE_INSTURMENTATION_RULE,
	&DELETE_NOISY_OPERATION_RULE,
	&ENABLE_SOURCE_PROFILING,
	&PERSIST_NAMESPACES,
	&PERSIST_SOURCES,
	&RECOVER_FROM_ROLLBACK,
	&RESET_LOCAL_UI_CONFIG_TO_FACTORY_DEFAULTS,
	&RESTART_POD,
	&RESTART_WORKLOADS,
	&TEST_DESTINATION_CONNECTION,
	&UPDATE_ACTION,
	&UPDATE_COST_REDUCTION_RULE,
	&UPDATE_DATA_STREAM,
	&UPDATE_DESTINATION,
	&UPDATE_HIGHLY_RELEVANT_OPERATION_RULE,
	&UPDATE_INSTURMENTATION_RULE,
	&UPDATE_LOCAL_UI_CONFIG,
	&UPDATE_LOCAL_UI_SAMPLING_CONFIG,
	&UPDATE_NOISY_OPERATION_RULE,
	&UPDATE_REMOTE_CONFIG,
	&UPDATE_SOURCE,
	&UPDATE_TOKEN,
}
