issuer: https://token.actions.githubusercontent.com
subject_pattern: '^repo:odigos-io(@84347062)?/odigos-central-client(@1187259475)?:ref:refs/heads/main$'

permissions:
  contents: write
  pull_requests: write
