issuer: https://token.actions.githubusercontent.com
subject_pattern: '^repo:odigos-io/odigos-enterprise:ref:refs/heads/main$'

permissions:
  # needed for odigos-enterprise to trigger the repository_dispatch event here
  contents: write
