issuer: https://token.actions.githubusercontent.com
subject_pattern: '^repo:odigos-io(@84347062)?/odigos-enterprise(@683608086)?:ref:refs/heads/main$'

permissions:
  # needed for odigos-enterprise to trigger the repository_dispatch event here
  contents: write
